language: php
php:
  - '5.6'
  - '7.0'
env:
  global:
    - MIN_PHP_VERSION="5.6"
    - AUTOLOAD_DIR="classes"
    - AUTOLOAD_EXTS=".php"
    - AUTOLOAD_FUNC="spl_autoload"
before_script:
  npm install
script: npm run test
